# Generated by Django 4.2.7 on 2026-06-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolroute',
            name='assigned_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift',
            field=models.CharField(default='Day', max_length=10),
        ),
        migrations.AlterField(
            model_name='patrolroute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to='api.userprofile'),
        ),
    ]
