# Generated by Django 4.2.7 on 2026-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patrolroute_assigned_guard_userprofile_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_system_admin',
            field=models.BooleanField(default=False),
        ),
    ]
