# Generated by Django 4.2.7 on 2026-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_is_system_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolroute',
            name='route_type',
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='conditional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='enforce_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='enforce_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='randomized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='operator_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('guard', 'Guard')], default='guard', max_length=20),
        ),
    ]
