# Generated by Django 4.2.7 on 2026-06-03 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_patrolroute_route_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_tag', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guard', 'Guard'), ('supervisor', 'Supervisor')], default='guard', max_length=20)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Flex', 'Flex')], default='Day', max_length=10)),
                ('nfc_tags_scanned', models.IntegerField(default=0)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('is_on_shift', models.BooleanField(default=False)),
                ('last_shift_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Flex', 'Flex')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.dispatcher')),
                ('guard_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.guardsupervisor')),
            ],
            options={
                'unique_together': {('dispatcher', 'guard_supervisor', 'is_active')},
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.checkpoint'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='api.device'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.patrolroute'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='guardsupervisor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guards_supervisors', to='api.organization'),
        ),
        migrations.AddField(
            model_name='guardsupervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatchers', to='api.organization'),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin',
            name='organizations',
            field=models.ManyToManyField(related_name='admins', to='api.organization'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='guard_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.guardsupervisor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_device', to='api.guardsupervisor'),
        ),
        migrations.AlterField(
            model_name='patrolroute',
            name='assigned_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='api.guardsupervisor'),
        ),
        migrations.AlterField(
            model_name='patrolroute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to='api.guardsupervisor'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
