# Generated by Django 4.2.7 on 2026-06-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dispatcher_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='nfc_tag',
        ),
        migrations.RemoveField(
            model_name='patrolroute',
            name='assigned_guard',
        ),
        migrations.RemoveField(
            model_name='patrolroute',
            name='conditional',
        ),
        migrations.RemoveField(
            model_name='patrolroute',
            name='randomized',
        ),
        migrations.AddField(
            model_name='organization',
            name='default_time_tolerance',
            field=models.IntegerField(default=15, help_text='Default minutes allowed for scheduled scans'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='is_geofence',
            field=models.BooleanField(default=False, help_text='If true, patrol relies on GPS perimeters'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='readout_text',
            field=models.TextField(blank=True, help_text='Instructional text for POC radio TTS'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, help_text='Time to alert operator to start', null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assignments', to='api.device'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='nfc_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='OperatorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.guardsupervisor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('security', 'Security Breach'), ('maintenance', 'Maintenance'), ('safety', 'Safety Hazard')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('guard_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='api.guardsupervisor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='api.organization')),
            ],
        ),
    ]
