# Generated by Django 4.2.7 on 2026-06-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_device_user_remove_dispatcher_nfc_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolroute',
            name='assigned_guards',
            field=models.ManyToManyField(blank=True, related_name='assigned_blueprints', to='api.guardsupervisor'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='send_start_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='start_alert_lead_time',
            field=models.IntegerField(default=15, help_text='Minutes before start to send alert'),
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('poi', 'POI'), ('geofence', 'Geofence')], max_length=20)),
                ('geometry', models.JSONField(help_text='Coordinate list for markers or polygons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_personnel', models.ManyToManyField(blank=True, related_name='assigned_map_objects', to='api.guardsupervisor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_objects', to='api.organization')),
            ],
        ),
    ]
