# Generated by Django 4.2.7 on 2026-06-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patrolroute_assigned_guards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolroute',
            name='is_audit',
            field=models.BooleanField(default=False, help_text='If true, guards scan other devices (Peer-to-Peer)'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_shifts', to='api.patrolroute'),
        ),
    ]
