# Generated by Django 4.2.7 on 2026-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_patrolroute_is_audit_patrolroute_is_emergency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
