# Generated by Django 4.2.7 on 2026-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_shiftassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolroute',
            name='is_daily',
            field=models.BooleanField(default=False, help_text='If true, this route resets and alerts daily'),
        ),
    ]
