# Generated by Django 4.2.7 on 2026-06-04 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_alter_patrolroute_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='dispatcher',
            field=models.ForeignKey(help_text='The Dispatcher or Admin who created this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
