# Generated by Django 4.2.7 on 2026-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_shiftassignment_dispatcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardsupervisor',
            name='user',
        ),
        migrations.AddField(
            model_name='guardsupervisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guardsupervisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
