# Generated by Django 4.2.7 on 2026-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_guardsupervisor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='can_manage_devices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='can_manage_guards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='can_manage_routes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guardsupervisor',
            name='auth_nfc_tag',
            field=models.CharField(blank=True, help_text='Physical NFC tag ID for guard login/auth', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
