# Generated by Django 4.2.7 on 2026-06-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_dispatcher_can_manage_devices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardsupervisor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardsupervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patrolroute',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.organization'),
        ),
    ]
