# Generated by Django 4.2.7 on 2026-06-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_shiftassignment_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id_snapshot', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisionings', to='api.device')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_provisionings', to='api.guardsupervisor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_provisionings', to='api.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'operator_id_snapshot'], name='api_devicep_organiz_be2514_idx')],
                'unique_together': {('device', 'guard')},
            },
        ),
    ]
