# Generated by Django 4.2.7 on 2026-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_deviceprovisioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
