# Generated by Django 4.2.7 on 2026-06-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_device_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardsupervisor',
            name='user',
        ),
    ]
