# Generated by Django 4.2.7 on 2026-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_guardsupervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardsupervisor',
            name='auth_nfc_tag',
            field=models.CharField(blank=True, help_text='Physical NFC tag ID for guard login/auth', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guardsupervisor',
            name='operator_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
