# Generated by Django 4.2.7 on 2026-06-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_guardsupervisor_auth_nfc_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardsupervisor',
            name='auth_nfc_tag',
        ),
    ]
