# Generated by Django 4.2.7 on 2026-06-06 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_remove_guardsupervisor_auth_nfc_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardsupervisor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardsupervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
