# Generated by Django 4.2.7 on 2026-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_guardsupervisor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='callsign',
            field=models.CharField(blank=True, help_text='System-generated hardware callsign', max_length=100, null=True),
        ),
    ]
