# Generated by Django 4.2.7 on 2026-06-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_device_callsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=100)),
                ('active_shift', models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night'), ('Flex', 'Flex')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_callsign_assignment', to='api.guardsupervisor')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_callsign', to='api.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callsign_registry', to='api.organization')),
            ],
            options={
                'unique_together': {('organization', 'operator_id')},
            },
        ),
    ]
