# Generated by Django 4.2.7 on 2026-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_callsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='dwell_time',
            field=models.IntegerField(default=0, help_text='Minutes expected to stay at checkpoint'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='radius',
            field=models.IntegerField(default=50, help_text='Acceptable GPS radius in meters'),
        ),
        migrations.AddField(
            model_name='guardsupervisor',
            name='proximity_radius',
            field=models.IntegerField(default=50, help_text='Proximity allowed for peer-to-peer verification (meters)'),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='radius',
            field=models.IntegerField(blank=True, help_text='Radius for POI/Circle objects', null=True),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='send_announcement',
            field=models.BooleanField(default=False, help_text='If true, the readout_text will be broadcasted.'),
        ),
    ]
