# Generated by Django 4.2.7 on 2026-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_checkpoint_dwell_time_checkpoint_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='auditor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
