# Generated by Django 4.2.7 on 2026-06-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_checkpoint_auditor_id_checkpoint_target_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='The date this mission is intended to occur', null=True),
        ),
    ]
