# Generated by Django 4.2.7 on 2026-06-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_shiftassignment_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
