# Generated by Django 4.2.7 on 2026-06-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_shiftassignment_scheduled_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardsupervisor',
            name='proximity_radius',
        ),
        migrations.AddField(
            model_name='device',
            name='proximity_radius',
            field=models.IntegerField(default=50, help_text='Proximity allowed for peer-to-peer verification (meters)'),
        ),
    ]
