# Generated by Django 4.2.7 on 2026-06-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_guardsupervisor_proximity_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='auditor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='dwell_time',
            field=models.IntegerField(default=0, help_text='Minutes expected to stay at location'),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='planned_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mapobject',
            name='geometry',
            field=models.JSONField(blank=True, help_text='Coordinate list for markers or polygons', null=True),
        ),
    ]
