# Generated by Django 4.2.7 on 2026-06-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_mapobject_auditor_id_mapobject_dwell_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='is_active_asset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_checkpoints', to='api.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='peer_session_key',
            field=models.CharField(blank=True, help_text='Rolling key for server-side scan verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='frequency',
            field=models.CharField(choices=[('once', 'One-Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('adhoc', 'Ad-Hoc/Flexible')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft/Staging'), ('scheduled', 'Scheduled/Upcoming'), ('active', 'Active/Daily'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='api.patrolroute'),
        ),
    ]
