# Generated by Django 4.2.7 on 2026-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_checkpoint_is_active_asset_checkpoint_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='dwell_time',
            field=models.IntegerField(blank=True, default=0, help_text='Minutes expected to stay at checkpoint'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='radius',
            field=models.IntegerField(blank=True, default=50, help_text='Acceptable GPS radius in meters'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='time_tolerance',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AlterField(
            model_name='patrolroute',
            name='frequency',
            field=models.CharField(blank=True, choices=[('once', 'One-Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('adhoc', 'Ad-Hoc/Flexible')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='patrolroute',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft/Staging'), ('scheduled', 'Scheduled/Upcoming'), ('active', 'Active/Daily'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
