# Generated by Django 4.2.7 on 2026-06-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_checkpoint_dwell_time_alter_checkpoint_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='entry_msg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='exit_msg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='geo_shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapobject',
            name='intrusion_alarm',
            field=models.BooleanField(default=False),
        ),
    ]
