# Generated by Django 4.2.7 on 2026-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_mapobject_entry_msg_mapobject_exit_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolroute',
            name='assigned_devices',
            field=models.ManyToManyField(blank=True, related_name='assigned_blueprints', to='api.device'),
        ),
    ]
