# Generated by Django 5.2.15 on 2026-06-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_patrolroute_assigned_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='guard_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.guardsupervisor'),
        ),
    ]
