# Generated by Django 4.2.7 on 2026-06-20 12:18

from django.db import migrations, models


def set_checkpoint_type(apps, schema_editor):
    Checkpoint = apps.get_model('api', 'Checkpoint')
    for cp in Checkpoint.objects.all():
        if cp.auditor_id and cp.target_id:
            cp.checkpoint_type = 'peer'
        elif cp.lat is not None and cp.lng is not None:
            cp.checkpoint_type = 'gps'
        elif cp.nfc_tag:
            cp.checkpoint_type = 'nfc'
        else:
            cp.checkpoint_type = 'nfc'
        cp.save(update_fields=['checkpoint_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_device_gps_fetch_requested_device_last_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_type',
            field=models.CharField(choices=[('nfc', 'NFC'), ('gps', 'GPS'), ('peer', 'Peer'), ('geo', 'Geofence')], default='nfc', max_length=10),
        ),
        migrations.RunPython(set_checkpoint_type, reverse_code=migrations.RunPython.noop),
    ]
