# Generated by Django 4.2.7 on 2026-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_checkpoint_checkpoint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='time_tolerance',
            field=models.IntegerField(default=15, help_text='Allowed time deviation in minutes'),
        ),
    ]
