# Generated by Django 5.2.15 on 2026-06-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_mapobject_time_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='fetch_location_on_scan',
            field=models.BooleanField(default=False, help_text='Auto-fetch GPS location on first NFC scan'),
        ),
    ]
