# Generated by Django 5.2.15 on 2026-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_mapobject_fetch_location_on_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='planned_duration_minutes',
            field=models.IntegerField(blank=True, default=5, help_text='Countdown duration in minutes for NFC scan window', null=True),
        ),
    ]
