# Generated by Django 5.2.15 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_mapobject_planned_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='checkpoint_type',
            field=models.CharField(blank=True, help_text='Frontend type: nfc, gps, geo, peer', max_length=20, null=True),
        ),
    ]
