# Generated by Django 5.2.15 on 2026-06-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_mapobject_checkpoint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery_pct',
            field=models.SmallIntegerField(blank=True, help_text='Device battery percentage 0-100', null=True),
        ),
    ]
