# Generated by Django 5.2.15 on 2026-06-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_device_battery_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, help_text='Device auth password, generated on registration', max_length=128, null=True),
        ),
    ]
