# Generated by Django 5.2.15 on 2026-06-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_device_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='carrier',
            field=models.CharField(blank=True, help_text='Mobile network carrier name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, help_text='IMEI number of the device', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Device manufacturer (e.g. Samsung)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, help_text='Device model (e.g. Galaxy S24)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='network_type',
            field=models.CharField(blank=True, help_text='Network type (e.g. 5G, 4G LTE)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, help_text='OS version (e.g. Android 14)', max_length=100, null=True),
        ),
    ]
