# Generated by Django 5.2.15 on 2026-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_add_device_hardware_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='device',
            name='network_type',
        ),
        migrations.AddField(
            model_name='device',
            name='imsi',
            field=models.CharField(blank=True, help_text='IMSI of the SIM card', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_phone_number',
            field=models.CharField(blank=True, help_text='SIM card phone number (MSISDN)', max_length=30, null=True),
        ),
    ]
