# Generated by Django 5.2.15 on 2026-06-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_update_device_hardware_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='proximity_radius',
        ),
    ]
