# Generated by Django 4.2.7 on 2026-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_device_type_and_proximity'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='next_announcement_text',
            field=models.TextField(blank=True, help_text='Per-checkpoint TTS announcement text', null=True),
        ),
    ]
