# Generated by Django 5.2.15 on 2026-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_checkpoint_next_announcement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='raw_nfc',
            field=models.JSONField(blank=True, help_text='Full NFC payload from device (UID, NDEF, tech, sensors)', null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='scan_type',
            field=models.CharField(blank=True, help_text="Server-determined: 'tag' or 'peer'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='validity_reason',
            field=models.CharField(blank=True, help_text='Human-readable explanation of the score', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='validity_score',
            field=models.FloatField(blank=True, help_text='0.0-1.0 probability that this scan is legitimate', null=True),
        ),
    ]
