# Generated by Django 5.2.15 on 2026-06-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_scan_record_validity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gps_accuracy_threshold',
            field=models.IntegerField(blank=True, default=10, help_text='Required GPS accuracy in meters for a valid fetch', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_gps_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy of the last GPS fix in meters', null=True),
        ),
    ]
