# Generated by Django 5.2.15 on 2026-06-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_gps_accuracy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatoralert',
            name='play_sound',
            field=models.BooleanField(default=True, help_text='Play notification sound on device'),
        ),
        migrations.AddField(
            model_name='operatoralert',
            name='tts_pitch',
            field=models.FloatField(default=1.0, help_text='TTS speech pitch override 0.5-2.0'),
        ),
        migrations.AddField(
            model_name='operatoralert',
            name='tts_rate',
            field=models.FloatField(default=1.0, help_text='TTS speech rate override 0.5-2.0'),
        ),
        migrations.AddField(
            model_name='operatoralert',
            name='tts_voice',
            field=models.CharField(blank=True, default='', help_text='TTS voice locale override', max_length=50),
        ),
        migrations.AddField(
            model_name='operatoralert',
            name='vibrate',
            field=models.BooleanField(default=True, help_text='Vibrate device on alert'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='tts_pitch',
            field=models.FloatField(default=1.0, help_text='TTS speech pitch 0.5-2.0'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='tts_rate',
            field=models.FloatField(default=1.0, help_text='TTS speech rate 0.5-2.0'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='tts_voice',
            field=models.CharField(blank=True, default='', help_text='TTS voice locale (e.g. en-US, en-GB-Standard-A)', max_length=50),
        ),
    ]
