# Generated by Django 5.2.15 on 2026-06-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_add_tts_and_alert_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('battery_pct', models.SmallIntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s at capture time', null=True)),
                ('bearing', models.FloatField(blank=True, help_text='Bearing in degrees', null=True)),
                ('recorded_at', models.DateTimeField(help_text='Device timestamp of capture')),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='Server receipt timestamp')),
                ('is_corrected', models.BooleanField(default=False, help_text='True if this point was adjusted by GPS correction')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trail_points', to='api.shiftassignment')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_points', to='api.device')),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['device', 'recorded_at'], name='api_devicet_device__2a458c_idx'), models.Index(fields=['device', 'assignment'], name='api_devicet_device__eb06c1_idx')],
            },
        ),
    ]
