# Generated by Django 5.2.15 on 2026-06-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_add_devicetrail_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='auditor_id',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='is_active_asset',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='auditor_id',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='checkpoint_type',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='dwell_time',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='nfc_tag',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='planned_time',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='mapobject',
            name='time_tolerance',
        ),
    ]
