# Generated by Django 5.2.15 on 2026-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_checkpoint_auditor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callsign',
            old_name='operator_id',
            new_name='callsign',
        ),
        migrations.RenameField(
            model_name='guardsupervisor',
            old_name='operator_id',
            new_name='callsign',
        ),
        migrations.AlterField(
            model_name='guardsupervisor',
            name='callsign',
            field=models.CharField(blank=True, help_text='User-facing identifier (e.g. H-01@twocan). Typed at login.', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='callsign',
            unique_together={('organization', 'callsign')},
        ),
    ]
