# Generated by Django 5.2.15 on 2026-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_rename_operator_id_callsign_callsign_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deviceprovisioning',
            name='api_devicep_organiz_be2514_idx',
        ),
        migrations.RenameField(
            model_name='deviceprovisioning',
            old_name='operator_id_snapshot',
            new_name='callsign_snapshot',
        ),
        migrations.AddIndex(
            model_name='deviceprovisioning',
            index=models.Index(fields=['organization', 'callsign_snapshot'], name='api_devicep_organiz_fe1995_idx'),
        ),
    ]
