# Generated by Django 5.2.15 on 2026-06-23 19:37

import re
from django.db import migrations, models


def derive_code(name):
    words = [w for w in re.split(r'[\s\-_&]+', name or '') if w]
    if not words:
        return 'ORG'
    code = ''.join(w[0] for w in words).upper()
    if len(code) == 1 and words and len(words[0]) >= 3:
        code = words[0][:3].upper()
    code = re.sub(r'[^A-Z0-9]', '', code)
    return code[:4] or 'ORG'


def backfill_codes(apps, schema_editor):
    Organization = apps.get_model('api', 'Organization')
    used = set()
    for org in Organization.objects.all().order_by('id'):
        base = derive_code(org.name)
        candidate = base
        n = 1
        while candidate in used:
            candidate = f"{base[:7]}{n}"
            n += 1
        org.code = candidate
        org.save(update_fields=['code'])
        used.add(candidate)


def remove_codes(apps, schema_editor):
    Organization = apps.get_model('api', 'Organization')
    Organization.objects.all().update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_deviceprovisioning_api_devicep_organiz_be2514_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, help_text='Short uppercase org code used as operator-ID prefix (e.g. TCN)', max_length=8, null=True, unique=True),
        ),
        migrations.RunPython(backfill_codes, remove_codes),
    ]
