# Generated by Django 5.2.15 on 2026-06-24 04:20

import re
from django.db import migrations


def derive_code(name):
    words = [w for w in re.split(r'[\s\-_&]+', name or '') if w]
    if not words:
        return 'ORG'
    code = ''.join(w[0] for w in words).upper()
    if len(code) == 1 and words and len(words[0]) >= 3:
        code = words[0][:3].upper()
    code = re.sub(r'[^A-Z0-9]', '', code)
    return code[:4] or 'ORG'


def fix_short_codes(apps, schema_editor):
    Organization = apps.get_model('api', 'Organization')
    used = set()
    for org in Organization.objects.all().order_by('id'):
        if len(org.code or '') <= 1:
            base = derive_code(org.name)
            candidate = base
            n = 1
            while candidate in used or Organization.objects.exclude(pk=org.pk).filter(code__iexact=candidate).exists():
                candidate = f"{base[:7]}{n}"
                n += 1
            org.code = candidate
            org.save(update_fields=['code'])
        used.add(org.code)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_organization_code'),
    ]

    operations = [
        migrations.RunPython(fix_short_codes, migrations.RunPython.noop),
    ]
