# Generated by Django 5.2.15 on 2026-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_fix_org_code_single_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
