# Generated by Django 5.2.15 on 2026-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_device_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tts_pending',
            field=models.TextField(blank=True, help_text='Pending TTS message to deliver on next heartbeat', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='tts_pending_at',
            field=models.DateTimeField(blank=True, help_text='When the pending TTS was queued', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='tts_pending_pitch',
            field=models.FloatField(default=1.0, help_text='Pitch override for pending TTS'),
        ),
        migrations.AddField(
            model_name='device',
            name='tts_pending_rate',
            field=models.FloatField(default=1.0, help_text='Rate override for pending TTS'),
        ),
        migrations.AddField(
            model_name='device',
            name='tts_pending_voice',
            field=models.CharField(blank=True, default='', help_text='Voice override for pending TTS', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='tts_pitch',
            field=models.FloatField(default=1.0, help_text='Default TTS speech pitch 0.5-2.0'),
        ),
        migrations.AddField(
            model_name='device',
            name='tts_rate',
            field=models.FloatField(default=1.0, help_text='Default TTS speech rate 0.5-2.0'),
        ),
        migrations.AddField(
            model_name='device',
            name='tts_voice',
            field=models.CharField(blank=True, default='en-US', help_text='Default TTS voice locale for this device', max_length=50),
        ),
    ]
