# Generated by Django 5.2.15 on 2026-06-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_device_tts_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoralert',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.guardsupervisor'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='api.checkpoint'),
        ),
    ]
