# Generated by Django 4.2.7 on 2026-06-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_device_reminder_and_geofence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tts_acked',
            field=models.BooleanField(default=True, help_text='True when device confirmed receipt of last tts_pending. If False, resend on next heartbeat.'),
        ),
    ]
