# Generated by Django 4.2.7 on 2026-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_device_tts_acked'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='nfc_mode',
            field=models.CharField(blank=True, default='auto', help_text="Server-assigned NFC mode: 'hce_emulator', 'hce_reader', 'tag_reader', 'auto'", max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='sdk_int',
            field=models.IntegerField(blank=True, help_text='Android API level (Build.VERSION.SDK_INT)', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='shift_mode',
            field=models.CharField(choices=[('simple', 'Simple (no shift tracking)'), ('structured', 'Structured (Day/Night/Flex)')], default='simple', help_text='Controls whether shift-based logic (Day/Night/Flex) is enforced', max_length=20),
        ),
    ]
