# Generated by Django 4.2.7 on 2026-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_add_sdk_int_shift_mode_nfc_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='dwell_seconds',
            field=models.IntegerField(blank=True, help_text='Actual seconds spent at checkpoint before this scan', null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='insufficient_dwell_time',
            field=models.BooleanField(default=False, help_text='True if guard left before dwell_time elapsed'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='out_of_sequence',
            field=models.BooleanField(default=False, help_text='True if scanned in wrong order per route sequence'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('emergency_active', 'Emergency Active'), ('cancelled', 'Cancelled'), ('handover', 'Handed Over')], default='active', help_text='Lifecycle status of the assignment', max_length=20),
        ),
    ]
