# Generated by Django 4.2.7 on 2026-06-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_scanrecord_dwell_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='precision_level',
            field=models.CharField(blank=True, choices=[('strict', 'Strict'), ('normal', 'Normal'), ('loose', 'Loose')], default='normal', help_text='Context-aware radius multiplier: strict=0.5x, normal=1x, loose=2x', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If False, device is decommissioned and all auth requests are rejected'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_sequence_id',
            field=models.IntegerField(default=0, help_text='Last processed monotonic sequence ID from this device for offline scan ordering'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, help_text='Original timestamp reported by the client device', null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='sequence_id',
            field=models.IntegerField(blank=True, help_text='Monotonic counter from the client for offline scan ordering', null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='server_received_timestamp',
            field=models.DateTimeField(blank=True, help_text='Server wall-clock time when the scan was received', null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='time_drift_seconds',
            field=models.IntegerField(blank=True, help_text='Seconds between client_timestamp and server_received_timestamp. Positive = client behind.', null=True),
        ),
    ]
