# Generated by Django 4.2.7 on 2026-06-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_checkpoint_precision_level_device_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='checkpoint_type',
            field=models.CharField(choices=[('nfc', 'NFC'), ('gps', 'GPS'), ('peer', 'Peer'), ('custom', 'Custom'), ('geo', 'Geofence')], default='nfc', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together={('route', 'order')},
        ),
    ]
