# Generated by Django 4.2.7 on 2026-06-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_checkpoint_checkpoint_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together=set(),
        ),
    ]
