# Generated by Django 4.2.7 on 2026-06-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_checkpoint_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='anomaly_flags',
            field=models.JSONField(blank=True, default=list, help_text='List of anomaly codes detected during dwell trail walk', null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='dwell_valid',
            field=models.BooleanField(default=False, help_text='True if dwell trail met checkpoint.dwell_time requirement'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='sensor_aided',
            field=models.BooleanField(default=False, help_text='True if sensor context upgraded a weak NFC score'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='sensor_context',
            field=models.JSONField(blank=True, help_text='Sensor context from device (pir, accel, proximity, gps_trail)', null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='time_drift_suspicious',
            field=models.BooleanField(default=False, help_text='True if client timestamp drift exceeded threshold'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Machine-readable verification notes (pipe-separated tags)', null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='mission_stage',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('deployed', 'Deployed'), ('active', 'Active'), ('completing', 'Completing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', help_text='Lifecycle stage of the mission', max_length=20),
        ),
        migrations.CreateModel(
            name='MissionStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, default='', max_length=20)),
                ('to_stage', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='api.shiftassignment')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.device')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scanrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', 'created_at'], name='api_mission_assignm_c33e96_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('authenticated', 'Authenticated'), ('on_route', 'On Route'), ('checkpoint_due', 'Checkpoint Due'), ('completing', 'Completing'), ('completed', 'Completed'), ('emergency_pause', 'Emergency Pause'), ('offline_buffering', 'Offline Buffering'), ('session_expired', 'Session Expired')], default='authenticated', max_length=20)),
                ('telemetry_interval_ms', models.IntegerField(default=60000)),
                ('constellation_required', models.BooleanField(default=False)),
                ('sensor_activation', models.CharField(choices=[('none', 'None'), ('pir_plus_accel', 'PIR + Accelerometer'), ('accel_only', 'Accelerometer Only')], default='none', max_length=20)),
                ('expected_checkpoint_radius', models.IntegerField(default=5)),
                ('tolerance_window_min', models.IntegerField(default=15)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('battery_pct_at_enter', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_sessions', to='api.shiftassignment')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.device')),
            ],
            options={
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='api_devices_device__ceb6da_idx'), models.Index(fields=['state'], name='api_devices_state_d8dd21_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_state', models.CharField(choices=[('authenticated', 'Authenticated'), ('on_route', 'On Route'), ('checkpoint_due', 'Checkpoint Due'), ('completing', 'Completing'), ('completed', 'Completed'), ('emergency_pause', 'Emergency Pause'), ('offline_buffering', 'Offline Buffering'), ('session_expired', 'Session Expired')], max_length=20)),
                ('first_alert_minutes', models.IntegerField(default=15)),
                ('repeat_minutes', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='api.organization')),
            ],
            options={
                'ordering': ['session_state'],
                'unique_together': {('organization', 'session_state')},
            },
        ),
    ]
