# Generated by Django 4.2.7 on 2026-06-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_scanrecord_anomaly_flags_scanrecord_dwell_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='radius',
            field=models.IntegerField(blank=True, default=5, help_text='Acceptable GPS radius in meters'),
        ),
    ]
