# Generated by Django 4.2.7 on 2026-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_checkpoint_radius'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['scheduled_date', 'order']},
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date this checkpoint is scheduled for. Null = unscheduled/always active.', null=True),
        ),
    ]
