# Generated by Django 4.2.7 on 2026-06-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_add_scheduled_date_to_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='If True, organization is soft-deleted and hidden from queries'),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrolroute',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='If True, route is soft-deleted and hidden from queries'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='guard_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='api.guardsupervisor'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='api.patrolroute'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_archived'], name='api_organiz_is_arch_983108_idx'),
        ),
        migrations.AddIndex(
            model_name='patrolroute',
            index=models.Index(fields=['is_archived'], name='api_patrolr_is_arch_7ef2c1_idx'),
        ),
    ]
