# Generated by Django 4.2.7 on 2026-06-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_relationship_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='area_of_interest',
            field=models.JSONField(blank=True, help_text='Polygon defining the operational area. Format: [[lat,lng],...]. Used to lock maps and validate checkpoint placement.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='operational_note',
            field=models.TextField(blank=True, help_text="Notes about this operational zone (e.g. 'Downtown patrol district')"),
        ),
    ]
